
language: node_js

node_js:
  - 4

env:
  matrix:
    - NODE_VERSION=0.10
    - NODE_VERSION=0.12
    - NODE_VERSION=4
    - NODE_VERSION=6
    - NODE_VERSION=node

before_script:
  - nvm install $NODE_VERSION

script:
  - npm run lint
  - npm run build
  - nvm exec $NODE_VERSION npm run test-cover

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

before_deploy:
  - npm run typedoc
deploy:
  provider: surge
  project: ./typedoc/
  domain: opentracing-javascript.surge.sh
  skip_cleanup: true
