
language: node_js

node_js:
  - 4

script:
  - npm run lint
  - npm run build
  - npm run test-cover

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

before_deploy:
  - npm run typedoc
deploy:
  provider: surge
  project: ./typedoc/
  domain: opentracing-javascript.surge.sh
  skip_cleanup: true
